language: java
jdk: openjdk8
addons:
  sonarcloud:
    organization: "domheal-github"
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean install sonar:sonar -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  slack: ${SLACK_TOKEN}#builds
